POVTAS_OSU/Models/CalendarOfEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace POVTAS_OSU.Models
{
    //Календарь мероприятий
    public class CalendarOfEvent
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Событие")]
        public string Event { get; set; }
        [Display(Name = "Дата")]
        public string Date { get; set; }

        [Display(Name = "Отчет")]
        public string ReportFile { get; set; }

        //[Key]
        //[ForeignKey("EventReportOf")]
        //public int EventReportId { get; set; }
        //public virtual EventReport EventReportOf { get; set; }
    }
}

POVTAS_OSU/Controllers/CalendarOfEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using POVTAS_OSU.Models;

namespace POVTAS_OSU.Controllers
{
    [Authorize(Roles = "admin")]
    public class CalendarOfEventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CalendarOfEvents
        public ActionResult Index()
        {
          
            return View(db.CalendarOfEvents.ToList());
        }

        // GET: CalendarOfEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarOfEvent calendarOfEvent = db.CalendarOfEvents.Find(id);
            if (calendarOfEvent == null)
            {
                return HttpNotFound();
            }
            return View(calendarOfEvent);
        }

        // GET: CalendarOfEvents/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: CalendarOfEvents/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Event,Date, ReportFile")] HttpPostedFileBase ReportFile, CalendarOfEvent calendarOfEvent)
        {
            if (ModelState.IsValid)
            {
                if (ReportFile != null)
                {
                    string filename = ReportFile.FileName;
                    ReportFile.SaveAs(Server.MapPath("/Files/" + filename));
                    calendarOfEvent.ReportFile = "/Files/" + filename;
                }
                db.CalendarOfEvents.Add(calendarOfEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(calendarOfEvent);
        }

        // GET: CalendarOfEvents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarOfEvent calendarOfEvent = db.CalendarOfEvents.Find(id);
            if (calendarOfEvent == null)
            {
                return HttpNotFound();
            }
   
            return View(calendarOfEvent);
        }

        // POST: CalendarOfEvents/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Event,Date,ReportFile")] HttpPostedFileBase ReportFile, CalendarOfEvent calendarOfEvent, string oldFile)
        {
            if (ModelState.IsValid)
            {
                if (ReportFile != null)
                {
                    string filename = ReportFile.FileName;
                    ReportFile.SaveAs(Server.MapPath("/Files/" + filename));
                    calendarOfEvent.ReportFile = "/Files/" + filename;
                }
                else calendarOfEvent.ReportFile = oldFile;
                db.Entry(calendarOfEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(calendarOfEvent);
        }

        // GET: CalendarOfEvents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarOfEvent calendarOfEvent = db.CalendarOfEvents.Find(id);
            if (calendarOfEvent == null)
            {
                return HttpNotFound();
            }
            return View(calendarOfEvent);
        }

        // POST: CalendarOfEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CalendarOfEvent calendarOfEvent = db.CalendarOfEvents.Find(id);
            db.CalendarOfEvents.Remove(calendarOfEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

POVTAS_OSU/Views/CalendarOfEvents/Create.cshtml
@model POVTAS_OSU.Models.CalendarOfEvent

@{
    ViewBag.Title = "Create";
}

<h2>Календарь мероприятий</h2>

@using (Html.BeginForm("Create", "CalendarOfEvents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Создать новую запись</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        @*<div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Event, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Event, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Event, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ReportFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.ReportFile, new { htmlAttributes = new { type = "file", required = "required" } })
                @Html.ValidationMessageFor(model => model.ReportFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Создать" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

POVTAS_OSU/Views/CalendarOfEvents/Delete.cshtml
@model POVTAS_OSU.Models.CalendarOfEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Календарь мероприятий</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Удаление</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportFile)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-primary" />
        </div>

        <div class="mt-3">
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

POVTAS_OSU/Views/CalendarOfEvents/Details.cshtml
@model POVTAS_OSU.Models.CalendarOfEvent

@{
    ViewBag.Title = "Details";
}

<h2>Календарь мероприятий</h2>

<div>
    <h4>Подробная информация</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад", "Index")
</p>

POVTAS_OSU/Views/CalendarOfEvents/Edit.cshtml
@model POVTAS_OSU.Models.CalendarOfEvent

@{
    ViewBag.Title = "Edit";
    string oldFile = Model.ReportFile;
}

<h2>Календарь мероприятий</h2>

@using (Html.BeginForm(Html.BeginForm("Edit", "CalendarOfEvents", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <input type="hidden" name="oldFile" value="@oldFile" />

        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Event, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Event, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Event, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="container-sm">
                @Html.EditorFor(model => model.ReportFile, new
                {
                    htmlAttributes = new
                    {
                        type = "file"
                    }
                })
                @Html.ValidationMessageFor(model => model.ReportFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

POVTAS_OSU/Views/CalendarOfEvents/Index.cshtml
@model IEnumerable<POVTAS_OSU.Models.CalendarOfEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Календарь мероприятий</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table table-hover">
    <tr style="background-color: #7abfff;">

        @*<th>
            @Html.DisplayNameFor(model => model.Id)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Event)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReportFile)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>

    @*<td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>*@
    <td class="table-light">
        @Html.DisplayFor(modelItem => item.Event)
    </td>
    <td class="table-light">
        @Html.DisplayFor(modelItem => item.Date)
    </td>
    <td class="table-light">
        <a href="@item.ReportFile">Скачать</a>
    </td>
    <td class="table-light">
        @Html.ActionLink("Редактирование", "Edit", new { id = item.Id }) |
        @*@Html.ActionLink("Подробнее", "Details", new { id = item.Id }) |*@
        @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>