POVTAS_OSU/Models/SupportStaff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace POVTAS_OSU.Models
{
    public class SupportStaff
    {
        public int Id { get; set; }

        [Display(Name = "Фамилия")]
        [RegularExpression(@"^[А-Я][а-яА-я\s]*$", ErrorMessage = "Фамилия введена неверно")]
        public string Surname { get; set; }

        [Display(Name = "Имя")]
        [RegularExpression(@"^[А-Я][а-яА-я\s]*$", ErrorMessage = "Имя введено неверно")]
        public string Name { get; set; }

        [Display(Name = "Отчество")]
        [RegularExpression(@"^[А-Я][а-яА-я\s]*$", ErrorMessage = "Отчество введено неверно")]
        public string PatronymicName { get; set; }

        [Display(Name = "Общий стаж работы")]
        [Range(0, 70, ErrorMessage = "Опыт работы должен содержать только цифры и не может превышать 70 лет")]
        public string WorkExperience { get; set; }

        [Display(Name = "Образование")]
        public string Education { get; set; }

        [Display(Name = "Фото")]
        [Required(ErrorMessage = "Добавьте фото сотрудника")]
        public string Photo { get; set; }

        [NotMapped]
        public string FullName { get { return Surname + " " + Name + " " + PatronymicName; } }

        
        public int PositionId { get; set; }
        public Position Position { get; set; }

        public int ChairId { get; set; }
        public Chair Chair { get; set; }
    }
}

POVTAS_OSU/Controllers/SupportStaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using POVTAS_OSU.Models;

namespace POVTAS_OSU.Controllers
{
    public class SupportStaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        

        // GET: SupportStaffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportStaff supportStaff = db.SupportStaffs.Find(id);
            if (supportStaff == null)
            {
                return HttpNotFound();
            }
            return View(supportStaff);
        }

        [Authorize(Roles = "admin")]
        // GET: SupportStaffs
        public ActionResult Index()
        {
            var supportStaffs = db.SupportStaffs.Include(s => s.Position);
            return View(supportStaffs.ToList());
        }

        // GET: SupportStaffs/Create
        public ActionResult Create()
        {
            ViewBag.PositionId = new SelectList(db.Positions, "Id", "Title");
            return View();
        }

        // POST: SupportStaffs/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Surname,Name,PatronymicName,WorkExperience,Education,Photo,PositionId,ChairId")] HttpPostedFileBase Photo, SupportStaff supportStaff)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    string filename = Photo.FileName;
                    Photo.SaveAs(Server.MapPath("/Images/" + filename));
                    supportStaff.Photo = "/Images/" + filename;
                }
                db.SupportStaffs.Add(supportStaff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PositionId = new SelectList(db.Positions, "Id", "Title", supportStaff.PositionId);
            return View(supportStaff);
        }

        // GET: SupportStaffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportStaff supportStaff = db.SupportStaffs.Find(id);
            if (supportStaff == null)
            {
                return HttpNotFound();
            }
            ViewBag.PositionId = new SelectList(db.Positions, "Id", "Title", supportStaff.PositionId);
            return View(supportStaff);
        }

        // POST: SupportStaffs/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Surname,Name,PatronymicName,WorkExperience,Education,Photo,PositionId,ChairId")] HttpPostedFileBase Photo, SupportStaff supportStaff, string oldPhoto)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    string filename = Photo.FileName;
                    Photo.SaveAs(Server.MapPath("/Images/" + filename));
                    supportStaff.Photo = "/Images/" + filename;
                }
                else supportStaff.Photo = oldPhoto;
                db.Entry(supportStaff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PositionId = new SelectList(db.Positions, "Id", "Title", supportStaff.PositionId);
            return View(supportStaff);
        }

        // GET: SupportStaffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportStaff supportStaff = db.SupportStaffs.Find(id);
            if (supportStaff == null)
            {
                return HttpNotFound();
            }
            return View(supportStaff);
        }

        // POST: SupportStaffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupportStaff supportStaff = db.SupportStaffs.Find(id);
            db.SupportStaffs.Remove(supportStaff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

POVTAS_OSU/Views/SupportStaffs/Create.cshtml
@model POVTAS_OSU.Models.SupportStaff

@{
    ViewBag.Title = "Create";
}



<h2>Учебно-вспомогательный персонал кафедры</h2>

@using (Html.BeginForm("Create", "SupportStaffs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Создание новой записи</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label fw-bold" })
                    <div class="container-sm">
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.WorkExperience, htmlAttributes: new { @class = "control-label fw-bold" })
                    <div class="container-sm">
                        @Html.EditorFor(model => model.WorkExperience, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WorkExperience, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label fw-bold" })
                    <div class="container-sm">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <div class="control-label container-sm mb-2"><b>Должность</b></div>
                    <div class="container-sm">
                        @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PatronymicName, htmlAttributes: new { @class = "control-label fw-bold" })
                    <div class="container-sm">
                        @Html.EditorFor(model => model.PatronymicName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PatronymicName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label fw-bold" })
                    <div class="container-sm">
                        @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label fw-bold" })
            <div class="container-sm">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { type = "file", required = "required" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <input type="submit" value="Создать" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

POVTAS_OSU/Views/SupportStaffs/Delete.cshtml
@model POVTAS_OSU.Models.SupportStaff

@{
    ViewBag.Title = "Delete";
}

<h2>Учебно-вспомогательный персонал кафедры</h2>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Удаление</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatronymicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatronymicName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkExperience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkExperience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChairId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChairId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-primary" />
        </div>

        <div class="mt-3">
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

POVTAS_OSU/Views/SupportStaffs/Details.cshtml
@model POVTAS_OSU.Models.SupportStaff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SupportStaff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatronymicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatronymicName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkExperience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkExperience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChairId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChairId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

POVTAS_OSU/Views/SupportStaffs/Edit.cshtml
@model POVTAS_OSU.Models.SupportStaff

@{
    ViewBag.Title = "Edit";
    string oldPhoto = Model.Photo;
}

<h2>Учебно-вспомогательный персонал</h2>

@using (Html.BeginForm(Html.BeginForm("Edit", "SupportStaffs", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Редактировать</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <input type="hidden" name="oldPhoto" value="@oldPhoto" />

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label fw-bold" })
                <div class="container-sm">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.WorkExperience, htmlAttributes: new { @class = "control-label fw-bold" })
                <div class="container-sm">
                    @Html.EditorFor(model => model.WorkExperience, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WorkExperience, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label fw-bold" })
                <div class="container-sm">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <div class="control-label container-sm mb-2"><b>Должность</b></div>
                <div class="container-sm">
                    @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.PatronymicName, htmlAttributes: new { @class = "control-label fw-bold" })
                <div class="container-sm">
                    @Html.EditorFor(model => model.PatronymicName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatronymicName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label fw-bold" })
                <div class="container-sm">
                    @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label container-sm fw-bold" })
        <div class="container-sm">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { type = "file" } })

        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

POVTAS_OSU/Views/SupportStaffs/Index.cshtml
@model IEnumerable<POVTAS_OSU.Models.SupportStaff>

@{
    ViewBag.Title = "Index";
}

<h2>Учебно-вспомогательный персонал кафедры</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table table-hover">
    <tr style="background-color: #7abfff; ">

        <th>
            ФИО
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position.Title)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatronymicName)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.WorkExperience)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Education)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.ChairId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td class="table-light">
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td class="table-light">
                @Html.DisplayFor(modelItem => item.Position.Title)
            </td>
            @*<td class="table-light">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="table-light">
                    @Html.DisplayFor(modelItem => item.PatronymicName)
                </td>*@
            <td class="table-light">
                @Html.DisplayFor(modelItem => item.WorkExperience)
            </td>
            <td class="table-light">
                @Html.DisplayFor(modelItem => item.Education)
            </td>
            <td class="table-light">
                <img src="@item.Photo" width="100 vh" height="130 vw" />
            </td>
            @*<td class="table-light">
                    @Html.DisplayFor(modelItem => item.ChairId)
                </td>*@
            <td class="table-light">
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Подробнее", "Details", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>